CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  rating star_rating NOT NULL,
  description text
);